name: gcloud auth and build script

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-central1
  REPO_NAME: build-test-script
  REPO_FORMAT: docker
  SOURCE_DIR: .
  COMMIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  #workflow_call:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest

    permissions: 
          contents: 'read'
          id-token: 'write'
          

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true 

    - name: 'Enable gcloudignore'
      run: 'gcloud config set gcloudignore/enabled true'

    #- name: Build and Push Container
    #  run: |
    #      gcloud artifacts repositories create "${{ env.REPO_NAME }}" \
    #      --repository-format="${{ env.REPO_FORMAT }}" \
    #      --location="${{ env.REGION }}"

    - name: Run build and submit script file
      run: |
       chmod +x ./build_and_submit.sh
       ./build_and_submit.sh
